# Site settings
title:          wiznut
description:    "Let's create and cherish moments of joy together. Dive in and let the happiness flow!"
url:            https://www.wiznut.com

# Author
author:
  name:         WiZNUT
  email:        help@wiznut.com
  url:          https://www.wiznut.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: help@wiznut.com
  github: https://github.com/psseo80
